Add provisioning Job to the Dev stage

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -124,3 +124,67 @@ stages:
               azureSubscription: 'TW'
               appName: '$(WebAppNameDev)'
               package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'
+
+- stage: 'Test'
+  displayName: 'Deploy to the Test environment'
+  dependsOn: Dev
+  jobs:
+  - job: Provision
+    displayName: 'Provision Azure App service'
+    pool:
+      vmImage: 'ubuntu-16.04'
+    variables:
+    - group: Release
+    steps:
+    - script: |
+        # Exit when any command returns a failure status.
+        set -e
+
+        # Write terraform.tfvars
+        echo 'resource_group_location = "'$(ResourceGroupLocation)'"' | tee terraform.tfvars
+        # Write backend.tfvars
+        echo 'resource_group_name' = "tf-storage-rg" | tee backend.tfvars
+        echo 'storage_account_name' = "'$(StorageAccountName)'" | tee backend.tfvars
+        echo 'container_name' = "tfstate" | tee backend.tfvars
+        echo 'key' = "test.state" | tee backend.tfvars
+        # Initialize Terraform
+        terraform init -input=false -backend-config="backend.tfvars"
+        # Apply terraform plan
+        terraform apply -input=false -auto-approve
+        # Get the app service name for Test environment
+        WebAppNameTest=$(terraform output appservice_name_test)
+        # Write Webapp name variable to pipeline
+        echo "##vso[task.setvariable variable=WebAppNameTest;isOutput=true]$WebAppNameTest"
+      name: 'RunTerraform'
+      displayName: 'Run Terraform'
+      env: 
+        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
+        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
+        ARM_TENANT_ID: $(ARM_TENANT_ID)
+        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
+  - deployment: Deploy
+    dependsOn: Provision
+    variables:
+      WebAppNameTest: $[dependencies.Provision.output['RunTerraform.WebAppNameTest']]
+    pool:
+      vmImage: 'ubuntu-16.04'
+    environment: Test
+    strategy: 
+      runOnce:
+        deploy:
+          steps:
+          - download: current
+            artifact: drop
+          - task: AzureWebApp@1
+            displayName: 'Azure App service deploy website'
+            inputs:
+              azureSubscription: 'TW'
+              appName: '$(WebAppNameTest)'
+              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'
+
+
+
+
+
+
+
